name: Update data

on:
  schedule:
    - cron:  '0 5-20/4 * * *' # runs 4 hours between 05:00-20:00 UTC
  workflow_dispatch:

jobs:
  update_data_artefact:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare data from git
      run: |
        git-history file occupancy.sqlite occupancy.csv --id gym
        python convert_sqlite_to-pkl.py --db occupancy.sqlite --output data.pkl
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: data-artifact
        path: data.pkl
    
